title postmarketOS Phosh (Firmware DTB)
linux /boot/vmlinuz
initrd /boot/initramfs
options console=tty0 earlycon=efifb keep_bootcon ignore_loglevel efi=novamap arm64.nopauth clk_ignore_unused pd_ignore_unused panic=0 nosplash pmos.debug-shell pmos_boot_uuid=0AB6-2552 pmos_root_uuid=99282e4c-7999-4f66-a5b4-d054120181e5 pmos_rootfsopts=defaults
