title postmarketOS Debug
linux /boot/vmlinuz
initrd /boot/initramfs
devicetree /boot/board.dtb
options console=ttyMSM0,115200 console=tty0 earlycon pmos_boot_uuid=0AB6-2552 pmos_root_uuid=99282e4c-7999-4f66-a5b4-d054120181e5 pmos_rootfsopts=defaults
