title postmarketOS Direct Root Shell (rdinit=/bin/sh)
linux /boot/vmlinuz
initrd /boot/initramfs
devicetree /boot/board.dtb
options console=tty0 earlycon=efifb keep_bootcon ignore_loglevel efi=novamap arm64.nopauth clk_ignore_unused pd_ignore_unused panic=0 rdinit=/bin/sh root=UUID=99282e4c-7999-4f66-a5b4-d054120181e5 rootwait
